### ISSUE TITLE
建议把@selector 做成block 形式的

### ISSUE THREAD

**Issue by oit63** [MISSAJJ/MAButtonTool#1]

**Comment by MISSAJJ** [comment]
真心谢谢你的留言^_^

刚开始的时候是有想过用block来封装@selector回传的想法，后又觉得如果封装block，创建时还得多写一行block回调的代码，反而弄复杂了。

谢谢你的建议，等空下来我会思考再多写一个block的方法，便于喜欢用block的盆友们调用

**Comment by oit63** [comment]
👍
