### ISSUE TITLE
...建议把Image参数从 NSString *改成UIImage *

### ISSUE THREAD

**Issue by oit63** [MISSAJJ/MAButtonTool#2]
我这样用的 
self.navigationController.navigationItem.rightBarButtonItem = [MAButtonTool createButtonWithImage:pauseImage position:MAButtonToolPostionRight type:MAButtonToolTypeCustom actionBlock:^(UIButton *btn) {

```
}];
```

写好才发现Image 参数是 NSString....
但是比如我用的是FontIcon 生成的图片...没办法传入NSString的..

**Comment by MISSAJJ** [comment]
请问FontIcon 生成的图片是什么格式？ 不是png的吗？

工具类的内核已经将UIImage的创建包涵在内了， 所以只需要将imageNamed参数所对应的string图片名传递进去就可以了， 如果图片资源是拉在Assets.xcassets里的，只需要写图片名， 如果是把图片资源拉在项目包目录里的，图片名需要包含图片后缀，这也是开发中的常规。

```
+ (UIButton *)createButton:(NSString * __nullable)imageStr
{
／／／内核中这一句已经在内部创建了UIImage了／／／
    UIImage * image = [UIImage imageNamed:imageStr];
／／／／／／／／／／／／／／／／／／／／／／／／
    UIButton* btn= [UIButton buttonWithType:UIButtonTypeCustom];
    btn.frame = CGRectMake(0, 0, 40, 40);
    [btn setImageEdgeInsets:UIEdgeInsetsMake(0, 0, 0, 0)];
    [btn setImage:image forState:UIControlStateNormal];
    //按钮发光
    [btn setShowsTouchWhenHighlighted:YES];
    [btn setAdjustsImageWhenHighlighted:YES]; 
    return btn;
}

```

**Comment by oit63** [comment]
FontIcon是用类似fontawesome 这些开源图标库，用字体生成的，所以运代码行前没有图。

**Comment by oit63** [comment]
嗯，参数可以做一个类型判断。如果是nsstring 就按现在这样，如果是uiimage 就直接使用

**Comment by MISSAJJ** [comment]
抱歉，由于大部分的项目都是有美工配合制作按钮PNG图片的， 所以对于项目中的图标是用fontawesome生成的方案的确实知之甚少。  

分享给你一个有MAC版本的可生成PNG图标的工具 http://iconion.com  ，可以根据需求对应@2X，@3X的尺寸生成对应的图标，这是我的一个外国同事分享给我的， 平时用这个比较多， 快速高效。

不过刚才我了解了下 https://github.com/alexdrone/ios-fontawesome , 大致了解了方案

```
 UIImage *github = [UIImage imageWithIcon:@"fa-github" backgroundColor:[UIColor purpleColor] iconColor:[UIColor colorWithRed:0.9 green:0.9 blue:0.9 alpha:255] iconScale:2.f fontSize:20];
```

通过fontawesome生成的图片是UIImage格式的， 所以套用我的工具类是没法用的

很感激你的启发，觉得用ios-fontawesome创建ICON会是一个很好的思路， 等我空下来会把ios-fontawesome融入到MAButtonTool工具类中的。

谢谢关注和启发^_^

**Comment by oit63** [comment]
嗯，我平时也用ionic的字体库，不过我不知道有这个工具，谢谢推荐

**Comment by MISSAJJ** [comment]
已经把ios-fontawesome融入到MAButtonTool工具类中了，不过代码写的比较仓促，估计还有思考不严谨的地方，欢迎多提高贵意见。晚安^_^～
